CREATE TABLE IF not exists hospital.ENCOUNTERS(
  ID VARCHAR(255) PRIMARY KEY,
  START TIMESTAMP  NOT NULL,
  STOP TIMESTAMP,
  PATIENT VARCHAR(255)  NOT NULL,
  Organization VARCHAR(255),
  Provider VARCHAR(255),
  Payer VARCHAR(255),
  EncounterClass VARCHAR(255),
  Code VARCHAR(255),
  DESCRIPTION TEXT,
  Base_Encounter_Cost FLOAT,
  Total_Claim_Cost FLOAT,
  Payer_Coverage FLOAT,
  REASONCODE VARCHAR(100),
  REASONDESCRIPTION TEXT,
  FOREIGN KEY (PATIENT) REFERENCES hospital.PATIENTS(ID)
);  