CREATE TABLE IF not exists hospital.CONDITIONS(
    START TIMESTAMP NOT NULL,
    STOP TIMESTAMP,
    PATIENT VARCHAR(255)  NOT NULL,
    ENCOUNTER VARCHAR(255),
    CODE VARCHAR(255),
    DESCRIPTION TEXT
);


