CREATE TABLE IF NOT exists hospital.MEDICATIONS(
    START TIMESTAMP  NOT NULL,
    STOP TIMESTAMP,
    PATIENT VARCHAR(255)  NOT NULL,
    Payer VARCHAR(255),
    ENCOUNTER VARCHAR(255),
    CODE VARCHAR(255),
    DESCRIPTION TEXT,
    Base_Cost FLOAT ,
    Payer_Coverage FLOAT,
    DISPENSES INT,
    TOTALCOST FLOAT,
    REASONCODE VARCHAR(255),
    REASONDESCRIPTION TEXT
);
